# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d765c6800f4911d62a790204bdedfa4227b934737da11a6d52a5fe22c8f430b6b7826c321beedfe3f2fab8d4816e4eebf06aa08d918f42b57f5ef8a12b77ce1d

test:
  secret_key_base: 8da439da90d9e8bfa86cdfd2944272c794a58b2dd564f0afc7ea35d8c3964e6468135486e8bc9d54098416b48dabd287dfc5ed947aba5604a8fc0c55ebb12b94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
